import { Space_Grotesk } from 'next/font/google';

import { Navbar } from '@/components/navbar/navbar';

import { Category } from '@estore/types/category';
import { API } from '@estore/utils/api';

const mont = Space_Grotesk({
  display: 'swap',
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await API.get<Category[]>('/categories');

  return (
    <html lang="en">
      <body className={mont.className}>
        <Navbar categories={categories} />
        <main className="pb-20 md:pb-0">{children}</main>
      </body>
    </html>
  );
}
